In [ ]:
#This project will feature analysis of lines from Shakespeare plays and efforts to predict what characters speak each line
#The prediction ability of this code will primarily depend a few different features: act and scene, play title and the length of each line
#The act and scene metric will come from the pre-established ActSceneLine data
#The play title and line length would have been native data from the 'Play' and 'PlayerLinenumber' columns respectively
#Dataset obtained from https://www.kaggle.com/kingburrito666/shakespeare-plays
#Unfortunately, I had run into a missing data error when training the first of my two models that I could not solve. As a result, I could not test the accuracy of my models with my processed dataset

In [ ]:
#The first thing to do is to load up the dataset to analyze the raw data

In [103]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics
df = pd.read_csv(r'Shakespeare_data.csv')
df

,Dataline,Play,PlayerLinenumber,ActSceneLine,Player,PlayerLine
0,1,Henry IV,NaN,NaN,NaN,ACT I
1,2,Henry IV,NaN,NaN,NaN,SCENE I. London. The palace.
2,3,Henry IV,NaN,NaN,NaN,"Enter KING HENRY, LORD JOHN OF LANCASTER, the ..."
3,4,Henry IV,1.0,1.1.1,KING HENRY IV,"So shaken as we are, so wan with care,"
4,5,Henry IV,1.0,1.1.2,KING HENRY IV,"Find we a time for frighted peace to pant,"
...,...,...,...,...,...,...
111391,111392,A Winters Tale,38.0,5.3.180,LEONTES,"Lead us from hence, where we may leisurely"
111392,111393,A Winters Tale,38.0,5.3.181,LEONTES,Each one demand an answer to his part
111393,111394,A Winters Tale,38.0,5.3.182,LEONTES,Perform'd in this wide gap of time since first
111394,111395,A Winters Tale,38.0,5.3.183,LEONTES,We were dissever'd: hastily lead away.
111395,111396,A Winters Tale,38.0,NaN,LEONTES,Exeunt

In [ ]:
#The next thing to do is to start cleaning and interpreting the data
#First, the stage direction lines will be stricken from the dataset to clean the data
#Next, the dataline column will be stricken from the dataset to keep the model from getting confused from pointless information
#Then, the ActSceneLine column will be split with an ActScene column and a Line column. The line column will be deleted as well, as the PlayerLineNumber column is a better descriptor
#Finally, the Player and Play columns will be encoded to ensure easier reading from the program

In [104]:
Clean_data = df[pd.notna(df['Player'])]
Clean_data = df[pd.notna(df['ActSceneLine'])]
Clean_data = Clean_data.drop(['Dataline'], axis = 1)
all_plays = df['Play'].unique()
play_list = all_plays.tolist()
#print(play_list) #obtains play titles

Clean_data[['ActScene','Line']] = Clean_data['ActSceneLine'].str.rsplit('.', 1, expand=True).astype('float') #get two different columns with the Act + Scene and the Lines
Clean_data = Clean_data.drop(['Line'], axis = 1)
Clean_data = Clean_data.drop(['ActSceneLine'], axis =1)
Clean_data = Clean_data.drop(['PlayerLine'], axis =1)


le = LabelEncoder()
le.fit(Clean_data['Play'])
Clean_data['Play'] = le.transform(Clean_data['Play'])

# le.fit(Clean_data['Player']) #This was the final part of the code that would not fix itself. There was an unknown error that did not allow me to proceed
# Clean_data['Player'] = le.transform(Clean_data['Player'])
Clean_data

        Play  PlayerLinenumber         Player  ActScene
3          9               1.0  KING HENRY IV       1.1
4          9               1.0  KING HENRY IV       1.1
5          9               1.0  KING HENRY IV       1.1
6          9               1.0  KING HENRY IV       1.1
7          9               1.0  KING HENRY IV       1.1
...      ...               ...            ...       ...
111390     2              38.0        LEONTES       5.3
111391     2              38.0        LEONTES       5.3
111392     2              38.0        LEONTES       5.3
111393     2              38.0        LEONTES       5.3
111394     2              38.0        LEONTES       5.3

[105153 rows x 4 columns]

In [ ]:
#There were initially plans to allow for another feature that noted which characters would show up in each scenes, but this was cut due to time constraints

In [ ]:
#Now, it is time to use Machine learning techniques to analyze the altered data
#The first method that I tried was the decision tree model

In [107]:
x = Clean_data.drop('Player', axis = 1)
y = Clean_data.Player

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25)

training_model = DecisionTreeClassifier()
training_model.fit(x_train, y_train)

ValueError: Input contains NaN

In [ ]:
y_pred = training_model.predict(x_test)

test_score = metrics.accuracy_score(y_test, y_pred)

In [ ]:
#Unfortunately, the NaN errors that were in my dataset did not allow me to go any further, so my time was cut short.

In [ ]:
#Originally, I was also going to try the random forest classifier model from scikit learn, but I had obviously ran out of time before I could do so.